name: hello sl
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: run sl
        run: |
          sudo apt update
          sudo apt install -y sl
          /usr/bin/sl
