name: Build Dockerfile and Push Github Package Registry

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1

    - name: Build Image
      run: |
        cd docker/ && make build && cd ../

    - name: Push Image
      run: |
        docker tag actions-example docker.pkg.github.com/nobiki/repo/actions-example:latest
        docker push docker.pkg.github.com/nobiki/repo/actions-example:latest
