name: Build Dockerfile and Push Github Package Registry

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1
    - uses: einaregilsson/build-number@v1

    - name: Build Image
      run: |
        cd docker/ && make build && cd ../
