name: jisaku-actions

on:
  push:
    branches:
      - jisaku-actions

jobs:
  hoge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: './.github/actions/jisaku-actions'
      - run: wait-for-it localhost:4444 -t 60
