name: Schedule - Get Connection Number

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  schedule-get-connection-number:
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
