name: Experiment
on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: List files
      run: ls

    - name: Create a repository dispatch event to trigger workflow
        run: |
          curl https://example.com
