name: xbrowser-python-ie

on:
  push:
    branches:
      - ie

jobs:
  e2e-ie:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: warrenbuckley/Setup-Nuget@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - run: pip install selenium==3.141.0
      - run: nuget install Selenium.WebDriver.IEDriver -Version 3.150.0
      - run: python hello.py
        env:
          BROWSER: ie
